apps/frontend/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'frontend'

# AJAX PATTERNS
urlpatterns = [
    re_path(r'^ajax/location-search$', location_search, name = 'location-search'),
    re_path(r'^ajax/place-search$', place_search, name = 'get-place'),
    re_path(r'^ajax/get-location$', get_location, name = 'get-location'),
    re_path(r'^ajax/place-filter/(?P<module>\w+)$', place_filter, name = "place-filter"),
]

apps/oneci/urls.py
from django.urls import path, include
# from rest_framework.routers import DefaultRouter

from apps.frontend.views.oneci import *

# router = DefaultRouter()
app_name = 'oneci'

# router.register(r'place-type', views.PlaceTypeViewSet)
# router.register(r'place', views.PlaceViewSet)

# urlpatterns = [
# path('', include(router.urls)),
# ]

# urlpatterns += router.urls


urlpatterns = [
    path('', PlaceListView.as_view(), name = "place-list"),
    path('place-search', PlaceSearchView.as_view(), name = "place-search"),
    path('<int:pk>', PlaceListView.as_view(), name = "place-detail"),
]

apps/wizall/urls.py
from django.urls import path, include
# from rest_framework.routers import DefaultRouter

from apps.frontend.views.wizall import *

# router = DefaultRouter()
app_name = 'wizall'

# router.register(r'place-type', views.PlaceTypeViewSet)
# router.register(r'place', views.PlaceViewSet)

# urlpatterns = [
# path('', include(router.urls)),
# ]

# urlpatterns += router.urls


urlpatterns = [
    path('', PlaceListView.as_view(), name = "place-list"),
    path('place-search', PlaceSearchView.as_view(), name = "place-search"),
    path('<int:pk>', PlaceListView.as_view(), name = "place-detail"),
]

django_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.utils.translation import ugettext_lazy

from django_backend.settings import cfg

admin.site.site_title = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))
admin.site.site_header = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))

urlpatterns = [
    path('', include('apps.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('apps.api.urls')),
    # path('api/oneci/', include('apps.oneci.urls')),
    # path('api/wizall/', include('apps.wizall.urls')),
    path('search/', include('apps.frontend.urls')),
    path('search/oneci/', include('apps.oneci.urls')),
    path('search/wizall/', include('apps.wizall.urls')),
    path('admin/', admin.site.urls),

]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Add 'prefix' to all urlpatterns
# urlpatterns = [re_path(r'^{}/'.format(settings.APP_URL_ENDPOINT), include(urlpatterns))]

if settings.DEBUG is True:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

handler500 = 'rest_framework.exceptions.server_error'
handler400 = 'rest_framework.exceptions.bad_request'

apps/frontend/models.py
from django.db import models

# Create your models here.

apps/frontend/views/ajax.py
import json
from datetime import datetime
from itertools import chain

from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

from apps.location.models import *
from apps.oneci.models import Place
from apps.wizall.models import SalePoint
from lib.config import django_logger
from lib.middleware import api_call, str_to_json, get_place_list_by_coords, get_fields_and_properties, JSONEncoder
from lib.resources import confs


@csrf_exempt
def place_search(request):
    post = request.POST
    place_name = post.get('place_name', '')
    place_type = post.get('place_type', '')

    status = False
    results = []

    place = Place.objects.all()
    if len(place_type) > 0:
        place = place.filter(type = place_type)
    if len(place_name) > 0:
        place = place.filter(name__icontains = place_name)

    if place:
        status = True
        results = list(place.values())

    data = {
        'status': status,
        'results': results,
    }

    return JsonResponse(data, safe = False)


@csrf_exempt
def location_search(request):
    post = request.POST
    location = post.get('location', None)

    status = False
    results = []

    cities_list = City.objects.filter(name__icontains = location).values()
    city = [dict(x, type = 'city') for x in cities_list]

    towns_list = Town.objects.filter(name__icontains = location).values()
    town = [dict(x, type = 'town') for x in towns_list]

    boroughs_list = Borough.objects.filter(name__icontains = location).values()
    borough = [dict(x, type = 'borough') for x in boroughs_list]

    values = sorted(chain(city, town, borough), key = lambda instance: instance['name'])

    if values:
        status = True
        results = values

    data = {
        'status': status,
        'results': results,
    }

    return JsonResponse(data, safe = False)


@csrf_exempt
def get_location(request):
    latitude = request.POST.get('latitude', None)
    longitude = request.POST.get('longitude', None)

    if latitude and longitude:
        geo_api = confs.get('api')['GEO_API']

        url = geo_api['url'].replace('{latitude}', latitude).replace('{longitude}', longitude)
        place = api_call(url = url, method = geo_api['method'], timeout = 5)

        if not hasattr(place, 'status_code'):
            out_msg = place["message"]
            django_logger.error("GEO API NOT REACHABLE !!! => {}".format(out_msg))

            return JsonResponse(None, safe = False)
        else:
            r = place.text
            return JsonResponse(json.loads(r))


@login_required
def place_filter(request, module):
    post = request.POST

    model = Place if module == 'oneci' else SalePoint
    # model = apps.get_model(module, model)

    geo_loc = str_to_json(post.get('geo_loc', ''))
    data = str_to_json(post.get('data', ''))
    place_filter = post.get('filter', '')

    search_result, count_search_result = None, 0

    place_result = {}
    from_geo_loc = False

    if place_filter == 'all':
        search_result = model.objects.all()
        count_search_result = search_result.count()
    if place_filter == 'distance':
        search_result = get_place_list_by_coords(model, geo_loc, data)
        count_search_result = len(search_result)
        from_geo_loc = True
    if place_filter == 'opened':
        data = [place['pk'] for place in data]
        current_time = datetime.now().time()
        search_result = model.objects.filter(pk__in = data) \
            .filter(Q(closing_time__isnull = True) | (Q(opening_time__lte = current_time) & Q(closing_time__gte = current_time)))

        count_search_result = search_result.count()

    if search_result:
        data = [get_fields_and_properties(Place, place, has_monitor = False) for place in search_result]
        place_result = json.dumps(data, cls = JSONEncoder)

    context = {
        'module': module,
        'from_geo_loc': from_geo_loc,
        'place_result': place_result,
        'place_list': search_result,
        'place_list_count': count_search_result,
    }

    template = render_to_string('frontend/layouts/partials/place-search.html', context)

    data = {
        'template': template,
    }

    return JsonResponse(data, safe = False)

apps/frontend/views/index.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'frontend/index.html'

    # paginate_by = cfg.get('SETTINGS', 'PAGINATE_BY')

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'place'
        context['page_name'] = 'place_list'
        context['page_title'] = 'Liste des centres'
        data = [get_fields_and_properties(Place, place, has_monitor = False) for place in self.object_list]
        place_result = json.dumps(data, cls = JSONEncoder)
        context['place_result'] = place_result
        context['search_form'] = PlaceSearchForm()

        return context

apps/frontend/views/oneci.py
import json
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import ListView

from apps.frontend.forms import ONECIPlaceSearchForm
from apps.oneci.models import Place
# from django_backend.settings import cfg
from lib.middleware import JSONEncoder, get_fields_and_properties, str_to_json, get_place_list_by_coords


class PlaceListView(LoginRequiredMixin, ListView):
    model = Place
    context_object_name = 'place_list'
    template_name = 'frontend/search/oneci.html'

    # paginate_by = cfg.get('SETTINGS', 'PAGINATE_BY')

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['module'] = 'oneci'
        context['menu'] = 'place'
        context['page_name'] = 'place_list'
        context['page_title'] = 'Liste des centres'
        data = [get_fields_and_properties(Place, place, has_monitor = False) for place in self.object_list]
        place_result = json.dumps(data, cls = JSONEncoder)
        context['place_result'] = place_result
        context['search_form'] = ONECIPlaceSearchForm()

        return context


class PlaceSearchView(LoginRequiredMixin, ListView):
    def post(self, request, *args, **kwargs):
        form = ONECIPlaceSearchForm(data = request.POST)
        post = form.data

        place_name = post.get('name', '')
        place_type = post.get('type', '')
        place_location = post.get('location', '')

        search_result = Place.objects.all()
        if len(place_type) > 0:
            search_result = search_result.filter(type = place_type)
        if len(place_name) > 0:
            search_result = search_result.filter(name__icontains = place_name)
        if len(place_location) > 0:
            search_result = search_result.filter(
                Q(city__name__icontains = place_location) |
                Q(town__name__icontains = place_location) |
                Q(borough__name__icontains = place_location)
            )

        data = [get_fields_and_properties(Place, place, has_monitor = False) for place in search_result]
        place_result = json.dumps(data, cls = JSONEncoder)

        context = {
            'module': 'oneci',
            'place_result': place_result,
            'place_list': search_result,
            'place_list_count': search_result.count(),
        }

        template = render_to_string('frontend/layouts/partials/place-search.html', context)

        data = {
            'template': template,
        }

        return JsonResponse(data, safe = False)


class PlaceFilterView(LoginRequiredMixin, ListView):
    model = Place

    def post(self, request, *args, **kwargs):
        post = request.POST

        geo_loc = str_to_json(post.get('geo_loc', ''))
        data = str_to_json(post.get('data', ''))
        place_filter = post.get('filter', '')

        search_result, count_search_result = None, 0

        place_result = {}
        from_geo_loc = False

        if place_filter == 'all':
            search_result = self.model.objects.all()
            count_search_result = search_result.count()
        if place_filter == 'distance':
            search_result = get_place_list_by_coords(self.model, geo_loc, data)
            count_search_result = len(search_result)
            from_geo_loc = True
        if place_filter == 'opened':
            data = [place['pk'] for place in data]
            current_time = datetime.now().time()
            search_result = self.model.objects.filter(pk__in = data) \
                .filter(Q(closing_time__isnull = True) | (Q(opening_time__lte = current_time) & Q(closing_time__gte = current_time)))

            count_search_result = search_result.count()

        if search_result:
            data = [get_fields_and_properties(Place, place, has_monitor = False) for place in search_result]
            place_result = json.dumps(data, cls = JSONEncoder)

        context = {
            'module': 'oneci',
            'from_geo_loc': from_geo_loc,
            'place_result': place_result,
            'place_list': search_result,
            'place_list_count': count_search_result,
        }

        template = render_to_string('frontend/layouts/partials/place-search.html', context)

        data = {
            'template': template,
        }

        return JsonResponse(data, safe = False)

apps/frontend/views/wizall.py
import json
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import ListView

from apps.frontend.forms import WIZALLPlaceSearchForm
from apps.wizall.models import SalePoint
# from django_backend.settings import cfg
from lib.middleware import JSONEncoder, get_fields_and_properties, str_to_json, get_place_list_by_coords


class PlaceListView(LoginRequiredMixin, ListView):
    model = SalePoint
    context_object_name = 'place_list'
    template_name = 'frontend/search/wizall.html'

    # paginate_by = cfg.get('SETTINGS', 'PAGINATE_BY')

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['module'] = 'wizall'
        context['menu'] = 'place'
        context['page_name'] = 'place_list'
        context['page_title'] = 'Liste des agents'
        data = [get_fields_and_properties(SalePoint, place, has_monitor = False) for place in self.object_list]
        place_result = json.dumps(data, cls = JSONEncoder)
        context['place_result'] = place_result
        context['search_form'] = WIZALLPlaceSearchForm()

        return context


class PlaceSearchView(LoginRequiredMixin, ListView):
    def post(self, request, *args, **kwargs):
        form = WIZALLPlaceSearchForm(data = request.POST)
        post = form.data

        place_name = post.get('name', '')
        place_type = post.get('type', '')
        place_location = post.get('location', '')

        search_result = SalePoint.objects.all()
        if len(place_type) > 0:
            search_result = search_result.filter(type = place_type)
        if len(place_name) > 0:
            search_result = search_result.filter(name__icontains = place_name)
        if len(place_location) > 0:
            search_result = search_result.filter(
                Q(city__name__icontains = place_location) |
                Q(town__name__icontains = place_location) |
                Q(borough__name__icontains = place_location)
            )

        data = [get_fields_and_properties(SalePoint, place, has_monitor = False) for place in search_result]
        place_result = json.dumps(data, cls = JSONEncoder)

        context = {
            'module': 'wizall',
            'place_result': place_result,
            'place_list': search_result,
            'place_list_count': search_result.count(),
        }

        template = render_to_string('frontend/layouts/partials/place-search.html', context)

        data = {
            'template': template,
        }

        return JsonResponse(data, safe = False)


class PlaceFilterView(LoginRequiredMixin, ListView):
    model = SalePoint

    def post(self, request, *args, **kwargs):
        post = request.POST

        geo_loc = str_to_json(post.get('geo_loc', ''))
        data = str_to_json(post.get('data', ''))
        place_filter = post.get('filter', '')

        search_result, count_search_result = None, 0

        place_result = {}
        from_geo_loc = False

        if place_filter == 'all':
            search_result = self.model.objects.all()
            count_search_result = search_result.count()
        if place_filter == 'distance':
            search_result = get_place_list_by_coords(self.model, geo_loc, data)
            count_search_result = len(search_result)
            from_geo_loc = True
        if place_filter == 'opened':
            data = [place['pk'] for place in data]
            current_time = datetime.now().time()
            search_result = self.model.objects.filter(pk__in = data) \
                .filter(Q(closing_time__isnull = True) | (Q(opening_time__lte = current_time) & Q(closing_time__gte = current_time)))

            count_search_result = search_result.count()

        if search_result:
            data = [get_fields_and_properties(SalePoint, place, has_monitor = False) for place in search_result]
            place_result = json.dumps(data, cls = JSONEncoder)

        context = {
            'module': 'wizall',
            'from_geo_loc': from_geo_loc,
            'place_result': place_result,
            'place_list': search_result,
            'place_list_count': count_search_result,
        }

        template = render_to_string('frontend/layouts/partials/place-search.html', context)

        data = {
            'template': template,
        }

        return JsonResponse(data, safe = False)

apps/wizall/views.py
from django.shortcuts import render

# Create your views here.

apps/frontend/templates/frontend/search/oneci.html
{% extends 'frontend/layouts/default.html' %}
{% load static thumbnail utils crispy_forms_tags %}
{% block title %}{{ page_title|default:"Bienvenue sur jerecherche.ci" }}{% endblock %}
{% block header %}
    <header class="header_in map_view">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-12">
                    <div id="logo">
                        <a href="{% url module|add:':place-list' %}">
                            <img src="{% static 'frontend/img/logo_triumf.png' %}" width="40" alt="" class="logo_sticky">
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 col-12">
                    <a href="#menu" class="btn_mobile">
                        <div class="hamburger hamburger--spin" id="hamburger">
                            <div class="hamburger-box">
                                <div class="hamburger-inner"></div>
                            </div>
                        </div>
                    </a>
                    <nav id="menu" class="main-menu float-left">
                        <ul>
                            <li class="{% if module == 'oneci' %}active{% endif %}"><span><a href="{% url 'oneci:place-list' %}">ONECI</a></span></li>
                            <li class="{% if module == 'wizall' %}active{% endif %}"><span><a href="{% url 'wizall:place-list' %}">WIZALL</a></span></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </header>
{% endblock %}

{% block content %}
    <main>
        <div class="container-fluid full-height">
            <div class="row row-height">
                <div class="col-lg-5 content-left order-md-last order-sm-last order-last">
                    <div id="results_map_view">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-10">
                                    {# <h4><strong class="object_list_count">{{ object_list.count }}</strong> resultats</h4> #}
                                    <h4>Faites une recherche ici <i class="fa fa-arrow-right"></i></h4>
                                </div>
                                <div class="col-2">
                                    <a href="#0" class="search_mob btn_search_mobile map_view"></a> <!-- /open search panel -->
                                </div>
                            </div>
                            <!-- /row -->
                            <div class="search_mob_wp">
                                <div class="custom-search-input-2 map_view">
                                    <form action="{% url module|add:':place-search' %}" method="post" id="place-search-form">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {{ search_form.name }}
                                            <i class="icon_search"></i>
                                        </div>
                                        <div class="form-group">
                                            {{ search_form.location }}
                                            <i class="icon_pin_alt"></i>
                                        </div>

                                        {{ search_form.type }}

                                        <input type="hidden" name="geo_loc">
                                        <input type="submit" class="place-search-submit" value="Rechercher">
                                    </form>
                                </div>
                            </div>
                            <!-- /search_mobile -->
                        </div>
                        <!-- /container -->
                    </div>
                    <!-- /results -->

                    <div class="filters_listing version_3">
                        <div class="container-fluid">
                            <ul class="clearfix">
                                <li>
                                    <div class="switch-field">
                                        <form id="place-filters">
                                            {% csrf_token %}
                                            <input type="radio" id="all" name="listing_filter" value="all" data-module="{{ module }}" checked>
                                            <label for="all">Tous</label>
                                            <input type="radio" id="distance" name="listing_filter" value="distance" data-module="{{ module }}">
                                            <label for="distance">Par distance</label>
                                            <input type="radio" id="opened" name="listing_filter" value="opened" data-module="{{ module }}">
                                            <label for="opened">Ouvert</label>
                                        </form>
                                    </div>
                                </li>
                                {% comment %}<li>
                                    <a class="btn_filt_map" data-toggle="collapse" href="#filters" aria-expanded="false" aria-controls="filters"
                                       data-text-swap="Less filters" data-text-original="More filters">More filters</a>
                                </li>{% endcomment %}
                            </ul>
                        </div>
                        <!-- /container -->
                    </div>
                    <!-- /filters -->

                    <div class="collapse map_view" id="filters">
                        <div class="container-fluid margin_30_5">
                            <h6>Rating</h6>
                            <div class="row">
                                <div class="col-md-6">
                                    <ul>
                                        <li>
                                            <label class="container_check">Superb 9+ <small>245</small>
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                            </label>
                                        </li>
                                        <li>
                                            <label class="container_check">Very Good 8+ <small>123</small>
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-md-6">
                                    <ul>
                                        <li>
                                            <label class="container_check">Good 7+ <small>32</small>
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                            </label>
                                        </li>
                                        <li>
                                            <label class="container_check">Pleasant 6+ <small>12</small>
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <h6>Tags</h6>
                            <div class="row">
                                <div class="col-md-6">
                                    <ul>
                                        <li>
                                            <label class="container_check">Wireless Internet
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                            </label>
                                        </li>
                                        <li>
                                            <label class="container_check">Smoking Allowed
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-md-6">
                                    <ul>
                                        <li>
                                            <label class="container_check">Wheelchair Accesible
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                            </label>
                                        </li>
                                        <li>
                                            <label class="container_check">Parking
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <!-- /row -->
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="add_bottom_30">
                                        <h6>Distance</h6>
                                        <div class="distance"> Radius around selected destination <span></span> km</div>
                                        <input type="range" min="10" max="100" step="10" value="30" data-orientation="horizontal">
                                    </div>
                                </div>
                            </div>
                            <!-- /row -->
                        </div>
                    </div>
                    <!-- /Filters -->

                    <div class="place-search-list {{ module }}">
                        {% include 'frontend/layouts/partials/place-search.html' %}
                    </div>

                    <p class="text-center add_top_30"><a href="#0" class="btn_1 rounded"><strong>Load more</strong></a></p>
                </div>
                <!-- /content-left-->

                <div class="col-lg-7 map-right">
                    <div id="map_right_listing"></div>
                    <!-- map-->
                </div>
                <!-- /map-right-->
            </div>
            <!-- /row-->
        </div>
        <!-- /container-fluid -->
    </main>
{% endblock %}